runtime: python
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: app.app

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10

manual_scaling:
      instances: 5