runtime: python
env: flex
entrypoint: uwsgi --http :$PORT --wsgi-file app.py --callable app

runtime_config:
  python_version: 3

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: app.app
