"""empty message

Revision ID: 573bb0068a15
Revises: e5227e6c07d4
Create Date: 2018-01-07 16:47:52.106421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573bb0068a15'
down_revision = 'e5227e6c07d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Reviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reviews',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Reviews_id_seq"\'::regclass)'), nullable=False),
    sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], name='Reviews_place_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Reviews_pkey')
    )
    # ### end Alembic commands ###
