"""empty message

Revision ID: e5227e6c07d4
Revises: e9b0becfe76e
Create Date: 2018-01-07 16:17:40.997698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5227e6c07d4'
down_revision = 'e9b0becfe76e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone1', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('address_city', sa.String(length=128), nullable=False),
    sa.Column('address_state', sa.String(length=2), nullable=False),
    sa.Column('address_zip', sa.String(length=5), nullable=False),
    sa.Column('address_country', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_profile', sa.Column('birthday', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'birthday')
    op.drop_table('Reviews')
    op.drop_table('place')
    # ### end Alembic commands ###
