"""empty message

Revision ID: e9b0becfe76e
Revises: b8bc7bb95412
Create Date: 2017-12-26 14:41:20.199013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b0becfe76e'
down_revision = 'b8bc7bb95412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone1', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('address_city', sa.String(length=64), nullable=True),
    sa.Column('address_state', sa.String(length=64), nullable=True),
    sa.Column('address_zip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('first_name', sa.String(length=64), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
